kind: pipeline
type: docker
name: ACG-FAKA🤡
steps:
clone:
  disable: true
steps:
# install
- name: 拉取代码
  image: images.elysia.li/alpine:latest
  volumes:
  - name: cache
    path: /faka
  commands:
  - apk update
  - apk add unzip wget
  - cd /faka
  - wget https://file.elysia.li/share/x-fWSlPN
  - mv x-fWSlPN acg-faka.zip
  - unzip acg-faka.zip
# Docker in Docker
- name: 自动构建
  image: images.elysia.li/dockeri:latest
  volumes:
  - name: cache
    path: /faka
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - apk add sudo curl wget
  - wget https://file.elysia.li/share/Qmfh1VCX
  - (mv Qmfh1VCX pack-v0.17.0-linux.tgz| sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
  #- (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.17.0/pack-v0.17.0-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
  - cd /faka/acg-faka
  - pack build images.elysia.li/acg-faka --builder images.elysia.li/builder:v1
# Update
- name: 上传镜像
  image: images.elysia.li/dockeri:latest
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - docker push images.elysia.li/acg-faka
# AUTO RM
- name: 清理镜像
  image: chaikair/dockeri:latest
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - docker image prune -f
  - docker volume prune -f
volumes:
- name: cache
  temp: {}
- name: docker-sock
  host:
   path: /var/run/docker.sock
